export const pricingPlans = [
  {
    name: "Beginner Program",
    price: "₹2,500",
    duration: "4–5 months",
    features: [
      "2–3 Live Classes per week",
      "Membership fee: ₹1,200/year",
      "Kit fee: ₹1,500 (one-time)",
      "Piece movement & basic rules",
      "Simple tactics: fork, pin, skewer",
      "Basic opening principles",
      "Certificate of completion",
      "Free demo class available",
    ],
  },
  {
    name: "Intermediate Program",
    price: "₹3,500",
    duration: "5–6 months",
    features: [
      "All Beginner Program inclusions",
      "Tactical combinations & calculation",
      "Opening repertoire & traps",
      "Endgame fundamentals",
      "Game analysis techniques",
      "Tournament exposure & guidance",
      "Monthly progress evaluation",
    ],
  },
  {
    name: "Advanced Program",
    price: "₹4,500",
    duration: "Ongoing",
    features: [
      "All Intermediate Program inclusions",
      "Deep opening preparation",
      "Complex endgames & strategy",
      "Tournament psychology coaching",
      "Personalized game review",
      "Rating improvement focus",
      "Priority support access",
    ],
  },
];